db_source:
    server: prd_server
    port: 5432
    database: rrhh_source_dummy
    user: rrhh_etl

db_destination:
    server: prd_server
    port: 5432
    database: rrhh_destination_dummy
    user: rrhh_etl
